spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: notifications-db
      uri: mongodb://mongodb:27017/notification_db

  mail:
    host: smtp.gmail.com
    port: 587
    username: hanbn210402@gmail.com
    password: obwkgjibhtecygzz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  main:
    allow-bean-definition-overriding: true